name: nightly
permissions:
  contents: write
on:
  schedule:
    - cron: '0 10 * * 1-5'
  push:
    paths:
      - '.github/workflows/nightly.yml'
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7 
      with: 
        script: |
          const releases = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          for (const release of releases.data) {
            if (release.tag_name === 'nightly') {
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.id,
              });
            }
          }
          try {
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/nightly`,
            });
          } catch (error) {}
  nightly:
    needs: init
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64
          - runner: ubuntu-latest
            target: x86
          - runner: ubuntu-latest
            target: aarch64
          - runner: ubuntu-latest
            target: armv7
          - runner: ubuntu-latest
            target: s390x
          - runner: ubuntu-latest
            target: ppc64le
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actboy168/action-zip@main
      id: zip
      with:
        name: swi-prolog-docs-${{ matrix.name }}
        path: |
          README.md
          LICENSE
    - uses: softprops/action-gh-release@v1
      with:
        name: nightly
        tag_name: nightly
        fail_on_unmatched_files: true
        files: ${{  steps.zip.outputs.output }}